---
grails:
    profile: web
    codegen:
        defaultPackage: eia
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: 'eia'
        version: '0.1'
        grailsVersion: '3.3.8'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true
---
grails:
    cors:
        enabled: true
---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
        upload:
            maxFileSize: 104857600
            maxRequestSize: 104857600
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true
server:
  port: 8380
  contextPath: /eia
---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: com.mysql.jdbc.Driver
    username: lh_eia_eia
    password: Lheia_eia@lhcis2018
    #username: root
    #password: root
environments:
    development:
        dataSource:
            dbCreate: update
            url: jdbc:mysql://localhost:3306/lh_eia_eia?useUnicode=true&characterEncoding=UTF-8&useSSL=false
            #logSql: true
            #formatSql: true
    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    production:
        dataSource:
            dbCreate: update
            url: jdbc:mysql://localhost:3306/lh_eia_eia?useUnicode=true&characterEncoding=UTF-8&useSSL=false
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: false
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
---
webroots:
    #cookie域名
    cookieDomain: lheia.lhcis.com
    #cookie路径
    cookiePath: /
    #session失效周期
    sessionTimeOut: 1800
    #上传下载文件路径
    filePath: /usr/local/software/mysql/upload/eiaUploadFiles/
    #显示上传图片路径
    eiaFileUrlPath: http://lheia.lhcis.com/eiaUploadFiles/
    authFileUrlPath: http://lheia.lhcis.com/authUploadFiles/
    #临时文件路径
    tempFilePath: /usr/local/tomcat/tomcat8.0_8380/temp/
    #原系统文件路径
    oldFilePath: /usr/local/software/mysql/upload/uploadFileLheia/
    #freemark模板路径
    exportContractFtlPath: /usr/local/tomcat/tomcat8.0_8380/webapps/eia/WEB-INF/classes/exportContract/
    #接口调用路径
    contextPath:
        api: http://172.16.5.30:8580/api/
    #流程接口调用路径,如注释则不发送流程消息至rtx
        wfapi: http://172.16.5.30:8580/api/
    #会话跳转路径
    forwardPath:
        auth: http://lheia.lhcis.com/auth/
        gis: http://lheia.lhcis.com/gis/
        eia: http://lheia.lhcis.com/eia/
    #HttpClient设置请求参数周期
    httpClientParams:
        #响应超时时间，超过此时间不再读取响应
        setSocketTimeout: 5000
        #链接建立的超时时间
        setConnectTimeout: 5000